name: Dependent Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      id: step1
      run: echo Hallo
    - name: Step 2
      if: steps.step1.outcome == 'success'
      run: echo Welt
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: Step 2
      run: echo Welt