name: Workflow commands showcase

on: [push]

jobs:
  showcase:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo my_env='Hallo' >> $GITHUB_ENV
      - name: Step 1
        run: |
          echo $my_env